config/routes.rb
Avis::Application.routes.draw do

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"  
  get "chat" => "sessions#chat", :as => "chat"

  resources :projects 
  post "projects/createComic"
  resources :items
  resources :comments
  resources :tasks
  resources :users
  resources :sessions
  resources :statuses
  resources :media

  root :to => 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  # Project is the overarching project and its subcategories (Pencils, inks, colours...)
  # Projects can have tasks assigned to them and comments, but they should not be able to 
  # have files. They are purely for indexing purposes. 
  # 
  # Variety should be comics, development, and web stuff
  # Dev would have the idea pot and resources
  # Web stuff would have AVIS and the main site
  attr_accessible :description, :name, :parent_id, :status, :variety
  
  has_many :comments, :as => "place"
  has_many :categories, :class_name => "Project", :foreign_key => "parent_id"
  has_many :tasks, :as => "project"
  has_many :items
  
  belongs_to :parent, :class_name => "Project"
  
  scope :comics, where(:parent_id => 0, :variety => 'Comic')
  
  #Project Statuses
  HIATUS = 0
  IN_PROGRESS = 1
  COMPLETED  = 2
  
  def self.create_comic(name, desc)
    @comic = Project.create(:name => name, :description => desc, :parent_id => 0,
          :status => Project::IN_PROGRESS, :variety => "Comic")
    @comic.categories.create(:name => "Notes", 
        :description => "Feel free to post random files pertaining to the comic here.", 
        :status => Project::IN_PROGRESS, :variety => "Comic")
    @comic.categories.create(:name => "Scripts", :description => "Scripts for the comic go here.", 
        :status => Project::IN_PROGRESS, :variety => "Comic")
    @comic.categories.create(:name => "Character Designs", 
        :description => "Designs for characters and costumes go here.", 
        :status => Project::IN_PROGRESS, :variety => "Comic")
    @comic.categories.create(:name => "Storyboards", 
        :description => "Storyboards and rough rough sketches for the pencils go here.", 
        :status => Project::IN_PROGRESS, :variety => "Comic")    
    @comic.categories.create(:name => "Pencils", :description => "Pencils go here.",
        :status => Project::IN_PROGRESS, :variety => "Comic")
    @comic.categories.create(:name => "Inks", :description => "Inked pages go here.", 
        :status => Project::IN_PROGRESS, :variety => "Comic")
    @comic.categories.create(:name => "Colours", :description => "Coloured pages go here.", 
        :status => Project::IN_PROGRESS, :variety => "Comic")
    @comic.categories.create(:name => "Letters", :description => "Lettered and final pages go here.", 
        :status => Project::IN_PROGRESS, :variety => "Comic")
    @comic
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authorize
  before_filter :authorize_admin, :only => "new"
  
  def index
    @projects = Project.comics
  end

  def show
    @project = Project.find(params[:id])
    if @project.name == "Admin" 
      authorize_admin
    end
    @comment = @project.comments.new
    @place = @project
    @item = Item.new
    @task = Task.new
    @taskplace = @project
    
    @isIdeaPot = (@project.name == "Idea Pot")
    #@file = File.new
  end
  
  def createComic
    @comic = Project.create_comic(params[:name], params[:description])
    redirect_to @comic, :notice => 'Comic was successfully created.'
  end

  def new
    @project = Project.new
    @projects = Project.comics
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, :notice => 'Project was successfully created.' }
        format.json { render :json => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.json { render :json => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, :notice => 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def summarize(content, wordcount=50)
    content.split[0..(wordcount-1)].join(" ") + (content.split.size > wordcount ? "... " : "") 
  end
end

app/views/projects/_form.html.slim
= form_for @project do |f|
  - if @project.errors.any?
    #error_explanation
      h2 = "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      ul
        - @project.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_area :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :status
    = f.select :status, [['In Progress', Project::IN_PROGRESS], 
        ['Hiatus', Project::HIATUS], 
        ['Completed', Project::COMPLETED]]
  .actions = f.submit 'Save'

app/views/projects/edit.html.slim
h1 Editing project

== render 'form'

= link_to 'Show', @project
'|
= link_to 'Back', projects_path

app/views/projects/index.html.slim
h1 Welcome to AVIS
p Catalytic Production's project manager

h2 Projects:
ul#comics
  - @projects.each do |project|
    li
      h3 = project.name
      ul#categories
        - project.categories.each do |category|
          li
            =link_to category.name, category
br{clear="all"}
ul.latest_comments            
  h2 = link_to "Latest Comments", comments_path
  - Comment.newest.limit(4).each do |comment|
    li 
      = link_to comment.place.name, comment.place
      = image_tag comment.user.avatar.url, :class => 'avi'
      br
      h3 =link_to comment.user.username, comment.user
      |  said 
      p.date
        | on 
        =comment.created_at 
      p
        = raw comment.content.bbcode_to_html

ul.latest_files
  h2 = link_to "Latest Uploads", media_path
  - Medium.newest.limit(4).each do |medium|
    li
      =link_to medium.name, medium
      br
      =link_to image_tag(thumbnail(medium)), medium

h2

app/views/projects/new.html.slim
h1 New project

= form_tag projects_createComic_path do
  p
    = text_field_tag :name, params[:name], :placeholder => "Name of Comic"
  p
    = text_area_tag :desc, params[:desc], :placeholder => "Description goes here"
  p.button	= submit_tag "Add Comic" 


= link_to 'Back', projects_path


table#projects_admin
  tr
    th 
    th Name
    th Description
    th
  - @projects.each do |project|
    tr
      td = image_tag status_image(project.status)
      td = project.name
      td = project.description
      td = link_to 'Edit', edit_project_path(project)

app/views/projects/show.html.slim
p#notice = notice

=render :template => 'layouts/breadcrumbs'
p.description
  = @project.description
/Subcategories
- if @project.categories.count > 0
  h2 Categories
  ul#categories
    -@project.categories.each do |cat|
      li = link_to cat.name, cat
      
- if @project.name != "AVIS" 
  /File upload form (only if leaf node???)
  - if @project.categories.count < 1
    =render :template => 'items/new' 
    
- if !@isIdeaPot
  /List Tasks and task field form???
  #task
    =render :template => 'tasks/new'
  /List Comments and Comment field form
  #comment
    =render :template => 'comments/new'
  h2 